Traceback (most recent call last):
  File "error_example2.py", line 5, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
